Исправлен переход между стартовым и регистрационным окнами.
Students-of-the-city-of-Kostroma/tournament-project pull request #11
Opened 2021-12-19 17:21 UTC by Tim-Shelll

Исправлена ошибка с закрытием стартового окна.

2021-12-19 17:31 UTC, YuriSilenok requested changes
гит показывает что изменились переносы строк, кто правит проект с линукса?

2021-12-19 17:34 UTC, Tim-Shelll commented
> гит показывает что изменились переносы строк, кто правит проект с линукса?

Я исправил переносы строк по стандарту Windows, предложила студия.

2021-12-19 17:55 UTC, YuriSilenok commented
> > гит показывает что изменились переносы строк, кто правит проект с линукса?
> 
> Я исправил переносы строк по стандарту Windows, предложила студия.

@MariaMakii а вы не на линуксе, случайно?

2021-12-19 17:58 UTC, YuriSilenok commented
> > гит показывает что изменились переносы строк, кто правит проект с линукса?
> 
> Я исправил переносы строк по стандарту Windows, предложила студия.

сейчас открыл оба проекта в 19 студии и студия не предложила мне что-то изменить в кодировке

2021-12-19 18:15 UTC, YuriSilenok commented
Что-то непонятное, но это может приводить к конфликтом в дальнейшем.

2021-12-19 18:18 UTC, YuriSilenok commented
@MariaMakii проверьте работу, мои комменты не в счет

2021-12-22 12:29 UTC, YuriSilenok commented
странно видеть исправления, если не зафиксированы замечания
@Tim-Shelll у вас конфликт версий

2021-12-22 16:45 UTC, YuriSilenok requested changes

2021-12-22 16:45 UTC, YuriSilenok commented on TournamentSoftware/MainWindow.xaml
> +                    <ImageBrush ImageSource="D:\ыыыыыы\tournament-project\images\burger_menu.png"/>
Должен быть относительный путь

2021-12-23 13:20 UTC, Tim-Shelll commented
> странно видеть исправления, если не зафиксированы замечания @Tim-Shelll у вас конфликт версий

Исправил конфликт версий

2021-12-23 20:06 UTC, YuriSilenok commented on TournamentSoftware/MainWindow.xaml
> +                    Content=""
Кажется я припоминаю что эти надписи должны перейти во всплывающую подсказку, появляющуюся при наведении на кнопку? @MariaMakii

2021-12-29 14:18 UTC, closed without merging

2021-12-29 14:19 UTC, Tim-Shelll commented
Исправил все проблемы в PR - FixTim #1

2021-12-30 12:39 UTC, YuriSilenok commented
ссылку не правильно оформили