Исправлен баг 81
Students-of-the-city-of-Kostroma/tournament-project pull request #112
Opened 2022-02-11 08:08 UTC by MariaMakii

2022-02-11 11:37 UTC, AndreyMaraj approved these changes
ok.

2022-02-11 18:06 UTC, urec-programmec requested changes
Добавьте в описание pull request описание сделанных изменений (вкратце, в чём была причина проблемы и какое решение было применено)

2022-02-11 18:32 UTC, MariaMakii commented
Описание бага подробно представлено [issue 81](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/issues/81).

**Проблема:** Дочерние элементы грида не сбрасывались при повторном открытии окна формирования групп и продолжали отрисовываться, из-за чего нажатие на кнопку приводило к ошибке (кнопка - один из детей грида, который не удалился).

**Решение:** Изменен подход к удалению дочерних элементов у гридов и вынесен в отдельный метод. Грид, у которого была описанная проблема, был перемещен внутрь внешнего грида, чтобы вместе с остальными детьми не удалялся лейбл с заголовком.

2022-02-13 06:49 UTC, YuriSilenok approved these changes

2022-02-13 12:46 UTC, YuriSilenok approved these changes

2022-02-13 12:50 UTC, merged