Исправлен баг 101
Students-of-the-city-of-Kostroma/tournament-project pull request #113
Opened 2022-02-11 08:18 UTC by MariaMakii

2022-02-11 18:04 UTC, urec-programmec requested changes
Добавьте описание причины сделанных изменений (вкратце, в чём была причина проблемы и какое решение было применено)

2022-02-11 18:45 UTC, MariaMakii commented
Описание бага подробно представлено [issue 101](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/issues/101)

**Проблема:** Открытый файл с таблицей регистрации нельзя загрузить в приложение, потому что это приводит к ошибке.

**Решение:** В метод Open добавлен параметр FileShare со значением ReadWrite, что дает доступ читать и записывать открытый файл.

2022-02-13 06:50 UTC, YuriSilenok approved these changes

2022-02-13 11:31 UTC, AndreyMaraj approved these changes

2022-02-13 11:40 UTC, merged