Исправление бага 17
Students-of-the-city-of-Kostroma/tournament-project pull request #132
Opened 2022-02-20 13:15 UTC by HappyRogue36

Описание бага подробно представлено [issue 17](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/issues/17)

**Проблема:** В поле можно ввести любые символы.

**Решение:** Добавлена проверка вводимых символов.

2022-02-22 05:42 UTC, YuriSilenok requested changes
У вас в целом большой файл получился, думаю что это потому, что у вас много логики в гуе

2022-02-22 05:42 UTC, YuriSilenok commented on TournamentSoftware/MainWindow.xaml.cs
> +            if ((CheckString >= 'a' && CheckString <= 'z') || (CheckString >= 'а' && CheckString <= 'я'))
Я так понимаю букве ё не фортануло

2022-02-22 05:49 UTC, YuriSilenok commented
Для устранения проблем с CI поднял задачу #135

2022-02-22 19:50 UTC, MariaMakii approved these changes

2022-02-24 17:28 UTC, HappyRogue36 commented on TournamentSoftware/MainWindow.xaml.cs
> +            if ((CheckString >= 'a' && CheckString <= 'z') || (CheckString >= 'а' && CheckString <= 'я'))
Поправлено

2022-02-24 21:18 UTC, MariaMakii approved these changes

2022-02-25 10:29 UTC, AndreyMaraj approved these changes

2022-02-26 12:44 UTC, merged