Issue 19
Students-of-the-city-of-Kostroma/tournament-project pull request #24
Opened 2021-12-28 21:41 UTC by MariaMakii

Исправлен баг №19
Добавление предыдущих номинаций к новым в формировании групп после загрузки файла

2021-12-30 12:59 UTC, AndreyMaraj requested changes
Looks OK

2022-01-03 16:16 UTC, YuriSilenok commented
Если выглядит нормально, почему выбрали пункт запрашивающий изменения?

2022-01-03 16:20 UTC, YuriSilenok approved these changes
почти все нормально, в вашей ветке оказался коммит который есть только в мастере, но не думаю что он нам как-то повредит. Так что даю добро.

2022-01-03 16:44 UTC, AndreyMaraj approved these changes

2022-01-03 21:53 UTC, merged