Проверка существования и создание несуществующих файлов для работы приложения
Students-of-the-city-of-Kostroma/tournament-project pull request #61
Opened 2022-01-27 20:19 UTC by MariaMakii

2022-01-28 14:18 UTC, AndreyMaraj submitted a review, later dismissed
Looks Ok

2022-01-28 16:55 UTC, urec-programmec commented
1) Please, add description to PR
2) You should move you changes to several commits, for example:
- method's names changes and other refactoring features
- the business logic's changes

2022-01-28 16:56 UTC, urec-programmec requested changes
1) Please, add description to PR
2) You should move you changes to several commits, for example:
- method's names changes and other refactoring features
- the business logic's changes

2022-01-28 17:21 UTC, MariaMakii commented
> 1. Please, add description to PR
> 2. You should move you changes to several commits, for example:
> 
> * method's names changes and other refactoring features
> * the business logic's changes


> 1. Please, add description to PR
> 2. You should move you changes to several commits, for example:
> 
> * method's names changes and other refactoring features
> * the business logic's changes

1. Пиши на русском
2. Описание добавлено
3. Не поняла что и как мне нужно сделать с коммитами

2022-01-29 15:43 UTC, YuriSilenok commented
Вам следует перенести свои изменения в несколько коммитов, например:
- изменения имен методов и другие функции рефакторинга
- изменения бизнес-логики

2022-01-29 15:45 UTC, YuriSilenok requested changes
Рефакторнг не связан с задачей #13
Пожалуйста, делайте рефакторнг только в предназначенных для этого ветках/задачах.

2022-01-30 17:17 UTC, AndreyMaraj approved these changes
Ok.

2022-01-31 03:39 UTC, YuriSilenok approved these changes

2022-02-02 05:06 UTC, closed without merging